//go:build !ignore_autogenerated

// Code generated by deepcopy. Hand-written (controller-gen unavailable); keep in
// sync with elasticnode_types.go by hand until controller-gen is in the toolchain.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies the receiver into out.
func (in *ElasticNode) DeepCopyInto(out *ElasticNode) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy returns a deep copy of the receiver.
func (in *ElasticNode) DeepCopy() *ElasticNode {
	if in == nil {
		return nil
	}
	out := new(ElasticNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a deep copy as a runtime.Object.
func (in *ElasticNode) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies the receiver into out.
func (in *ElasticNodeList) DeepCopyInto(out *ElasticNodeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		l := make([]ElasticNode, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&l[i])
		}
		out.Items = l
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *ElasticNodeList) DeepCopy() *ElasticNodeList {
	if in == nil {
		return nil
	}
	out := new(ElasticNodeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a deep copy as a runtime.Object.
func (in *ElasticNodeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies the receiver into out.
func (in *ElasticNodeSpec) DeepCopyInto(out *ElasticNodeSpec) {
	*out = *in
}

// DeepCopy returns a deep copy of the receiver.
func (in *ElasticNodeSpec) DeepCopy() *ElasticNodeSpec {
	if in == nil {
		return nil
	}
	out := new(ElasticNodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *ElasticNodeStatus) DeepCopyInto(out *ElasticNodeStatus) {
	*out = *in
	if in.LastTransitionTime != nil {
		out.LastTransitionTime = in.LastTransitionTime.DeepCopy()
	}
	if in.Conditions != nil {
		l := make([]metav1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&l[i])
		}
		out.Conditions = l
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *ElasticNodeStatus) DeepCopy() *ElasticNodeStatus {
	if in == nil {
		return nil
	}
	out := new(ElasticNodeStatus)
	in.DeepCopyInto(out)
	return out
}
